#!/bin/bash
#==============================================================#
# 脚本名     :   PG_RPM_ShellInstall.sh
# 创建时间   :   2024-03-08 22:00:00
# 更新时间   :   2024-03-09 23:00:00
# 描述      :    PostgreSQL 数据库RPM离线一键安装脚本（单机）
# Linux系统 :    Liunx7
# PG版本    :    15.6
# 脚本路径   :   /opt
# 版本      :   1.0.0
# 作者      :   公众号:IT邦德，PostgreSQL ACE Partner
# 说明      :   其他版本替换相应的RPM包即可
#==============================================================#
#==============================================================#
#                         基础参数                              #
#==============================================================#
##需要设置的参数
#本机服务器IP
export MY_SERVER_IP=192.168.3.20
#本机服务器主机名
export MY_HOSTNAME=pghost
#PostgreSQL相关RPM包上传根目录
export MY_SOFT_BASE=/opt
#PG依赖
export MY_RPM=libzstd-1.5.5-1.el7.x86_64.rpm
#PG相关RPM包
export MY_PG_RPM1=postgresql15-libs-15.6-1PGDG.rhel7.x86_64.rpm
export MY_PG_RPM2=postgresql15-15.6-1PGDG.rhel7.x86_64.rpm
export MY_PG_RPM3=postgresql15-server-15.6-1PGDG.rhel7.x86_64.rpm
##PG RPM包存放的目录
export MY_DIRECTORY_SOFT=$MY_SOFT_BASE
##PG脚本存放的目录
export MY_DIRECTORY_SCRIPT=$MY_SOFT_BASE
#==============================================================#
#           PG安装相关配置                                       #
#==============================================================#
#PG根目录
export MY_PG_HOME=/pgccc
#PG数据目录
export PGDATA=$MY_PG_HOME/pgdata
#PG家目录
export PGHOME=/usr/pgsql-15
##判断依赖是否上传
if [ -f $MY_DIRECTORY_SOFT/$MY_RPM ]; then 
    echo "PG RPM Already Upload"
else
    echo "Please Upload PG RPM First"
    exit
fi
#==============================================================#
#           1.安装前准备工作                                     #
#==============================================================#
## 1.1 设置主机名
hostnamectl set-hostname $MY_HOSTNAME
sed -i '/^HOSTNAME=/d' /etc/sysconfig/network
echo "HOSTNAME=$MY_HOSTNAME" >> /etc/sysconfig/network
echo "1.1 Configure hostname completed."
## 1.2 修改hosts
cp /etc/hosts /tmp/confbak
cat >> /etc/hosts <<EOF
$MY_SERVER_IP $MY_HOSTNAME
EOF
echo "1.2 Configure Hosts Completed."
## 1.3 安装PG依赖及RPM包
cd $MY_DIRECTORY_SOFT
rpm -ivh $MY_RPM  >/dev/null 2>&1
rpm -ivh $MY_PG_RPM1  >/dev/null 2>&1
rpm -ivh $MY_PG_RPM2  >/dev/null 2>&1
rpm -ivh $MY_PG_RPM3  >/dev/null 2>&1
echo "1.3 Install rpm Software Completed."
## 1.4 关闭防火墙
systemctl stop firewalld.service  >/dev/null 2>&1
systemctl disable firewalld.service  >/dev/null 2>&1 
systemctl status firewalld.service  >/dev/null 2>&1
echo "1.4 Disable Firewalld Service Completed."
## 1.5 关闭SELinux
sed -i '/^SELINUX=/d' /etc/selinux/config
echo "SELINUX=disabled" >> /etc/selinux/config
# cat /etc/selinux/config|grep "SELINUX=disabled"
setenforce 0 >/dev/null 2>&1
echo "1.5 Disable SELINUX Completed."
## 1.6 创建相关目录
mkdir -p $MY_PG_HOME/{pgdata,archive,scripts,backup,pgsql-15,soft}
chown -R postgres:postgres $MY_PG_HOME
chmod -R 775 $MY_PG_HOME
echo "1.6 PG Directories Created Completed."
## 1.7 修改postgres用户环境变量
echo 'export PS1="[\u@\h \W]\$"'  >> /var/lib/pgsql/.bash_profile
su - postgres -c "
cat >> /var/lib/pgsql/.bash_profile <<EOF
export LANG=en_US.UTF-8
export PGPORT=5432
export PGDATA=$PGDATA
export PGHOME=$PGHOME
export PATH=$PGHOME/bin:$PATH:.
export PGUSER=postgres
export PGDATABASE=postgres
EOF
"
source /var/lib/pgsql/.bash_profile >/dev/null 2>&1
echo "1.7 Configure postgres Env Completed."
#==============================================================#
#           2.PG数据库安装工作                                    #
#==============================================================#
## 2.1 数据库初始化
su - postgres -c "initdb -U postgres -E utf8 -D $PGDATA"
echo "2.1 database initialized Completed."

## 2.2 配置数据库参数
su - postgres -c "
cat >> $PGDATA/postgresql.conf <<EOF
listen_addresses = '*'
port=5432
logging_collector = on
log_directory = 'pg_log'
log_filename = 'postgresql-%a.log'
log_truncate_on_rotation = on
EOF
"
echo "postgresql.conf successfully"
su - postgres -c "
cat > $PGDATA/pg_hba.conf << EOF
# TYPE  DATABASE    USER    ADDRESS       METHOD
local     all       all                    trust
host      all       all   127.0.0.1/32     trust
host      all       all    0.0.0.0/0      md5
host   replication  all    0.0.0.0/0      md5
local  replication  all                    trust
EOF
"
echo "pg_hba.conf successfully"
#==============================================================#
#           3.开机自启管理                                       #
#==============================================================#
## 3.1 Server配置
cat >> /etc/systemd/system/postgresql.service <<EOF
[Unit]
Description=postgresql.service  
After=network.target
[Service]
Type=forking
User=postgres      
Group=postgres
WorkingDirectory=/var/lib/pgsql
ExecStart=$PGHOME/bin/pg_ctl start -D $PGDATA
ExecReload=$PGHOME/bin/pg_ctl restart -D $PGDATA
ExecStop=$PGHOME/bin/pg_ctl stop -D $PGDATA
PrivateTmp=true
[Install]
WantedBy=multi-user.target
EOF
echo "3.1 postgresql.service Add successfully"
## 3.2 服务加载
systemctl daemon-reload
systemctl start postgresql.service
systemctl enable postgresql.service
echo "3. service Load successfully"
echo "PostgreSQL successfully installed"
